minimum_pre_commit_version: "4.0.0"

repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: 5eab48332cc48565864514e3bc6de89df091a7c4
    hooks:
      - id: betterleaks-system
        stages: [pre-commit]
