from __future__ import annotations

from spy_market_agent.shadow.freshness import evaluate_market_data_freshness
from spy_market_agent.shadow.identity import shadow_run_identity, shadow_run_identity_payload
from spy_market_agent.shadow.model_gate import (
    ShadowModelAdmissionError,
    evaluate_model_admission,
    require_model_admission,
    validate_shadow_model_metadata,
)
from spy_market_agent.shadow.monitoring import build_monitoring_state, monitoring_event
from spy_market_agent.shadow.persistence import (
    SHADOW_DB_SCHEMA_VERSION,
    ShadowAlertRecord,
    ShadowHealthEventRecord,
    ShadowInputSnapshotRecord,
    ShadowOperationalRunStatus,
    ShadowPersistenceError,
    ShadowRecoveryRequiredError,
    ShadowRunNotFoundError,
    ShadowRunRecord,
    ShadowSchemaError,
    ShadowSQLiteRepository,
    ShadowStoredRun,
    initialize_shadow_database,
)
from spy_market_agent.shadow.persistence import (
    ShadowDuplicateRunError as ShadowDurableDuplicateRunError,
)
from spy_market_agent.shadow.policy import (
    DuplicateShadowRunError,
    ShadowPolicyError,
    evaluate_observation_only_run,
    evaluate_shadow_run,
)
from spy_market_agent.shadow.runner import (
    PHASE4_SHADOW_ADJUSTMENT_POLICY,
    SHADOW_OPERATION_CONFIGURATION_VERSION,
    SHADOW_OPERATION_FEATURE_SCHEMA,
    ShadowObservationResult,
    ShadowOperationalError,
    ShadowOperationalSnapshot,
    VerifiedShadowInput,
    build_operational_snapshot,
    date_to_identity_text,
    latest_completed_xnys_session,
    require_explicit_utc_datetime,
    run_observation,
    verify_phase1_shadow_input,
)
from spy_market_agent.shadow.schedule import (
    ShadowScheduleDecision,
    ShadowScheduleInput,
    evaluate_shadow_schedule,
)
from spy_market_agent.shadow.types import (
    BLOCKED_NO_APPROVED_MODEL,
    MODEL_CONNECTED_MODE,
    NO_APPROVED_SHADOW_MODEL,
    OBSERVATION_ONLY_MODE,
    PHASE4_PHASE_ID,
    PHASE4_SHADOW_RUN_ID_VERSION,
    PHASE4_SHADOW_SCHEMA_VERSION,
    PHASE4_TARGET_RELEASE,
    DailyMarketDataStatus,
    DataSnapshotLineage,
    FreshnessDecision,
    FreshnessStatus,
    HypotheticalTargetState,
    ModelAdmissionDecision,
    ModelAdmissionStatus,
    ProposalStatus,
    ShadowHealthStatus,
    ShadowMode,
    ShadowModelMetadata,
    ShadowMonitoringEvent,
    ShadowMonitoringState,
    ShadowProposal,
    ShadowRunConfiguration,
    ShadowRunDecision,
    ShadowRunRequest,
    ShadowRunStatus,
)

__all__ = [
    "BLOCKED_NO_APPROVED_MODEL",
    "MODEL_CONNECTED_MODE",
    "NO_APPROVED_SHADOW_MODEL",
    "OBSERVATION_ONLY_MODE",
    "PHASE4_PHASE_ID",
    "PHASE4_SHADOW_ADJUSTMENT_POLICY",
    "PHASE4_SHADOW_RUN_ID_VERSION",
    "PHASE4_SHADOW_SCHEMA_VERSION",
    "PHASE4_TARGET_RELEASE",
    "SHADOW_DB_SCHEMA_VERSION",
    "SHADOW_OPERATION_CONFIGURATION_VERSION",
    "SHADOW_OPERATION_FEATURE_SCHEMA",
    "DailyMarketDataStatus",
    "DataSnapshotLineage",
    "DuplicateShadowRunError",
    "FreshnessDecision",
    "FreshnessStatus",
    "HypotheticalTargetState",
    "ModelAdmissionDecision",
    "ModelAdmissionStatus",
    "ProposalStatus",
    "ShadowAlertRecord",
    "ShadowDurableDuplicateRunError",
    "ShadowHealthEventRecord",
    "ShadowHealthStatus",
    "ShadowInputSnapshotRecord",
    "ShadowMode",
    "ShadowModelAdmissionError",
    "ShadowModelMetadata",
    "ShadowMonitoringEvent",
    "ShadowMonitoringState",
    "ShadowObservationResult",
    "ShadowOperationalError",
    "ShadowOperationalRunStatus",
    "ShadowOperationalSnapshot",
    "ShadowPersistenceError",
    "ShadowPolicyError",
    "ShadowProposal",
    "ShadowRecoveryRequiredError",
    "ShadowRunConfiguration",
    "ShadowRunDecision",
    "ShadowRunNotFoundError",
    "ShadowRunRecord",
    "ShadowRunRequest",
    "ShadowRunStatus",
    "ShadowSQLiteRepository",
    "ShadowScheduleDecision",
    "ShadowScheduleInput",
    "ShadowSchemaError",
    "ShadowStoredRun",
    "VerifiedShadowInput",
    "build_monitoring_state",
    "build_operational_snapshot",
    "date_to_identity_text",
    "evaluate_market_data_freshness",
    "evaluate_model_admission",
    "evaluate_observation_only_run",
    "evaluate_shadow_run",
    "evaluate_shadow_schedule",
    "initialize_shadow_database",
    "latest_completed_xnys_session",
    "monitoring_event",
    "require_explicit_utc_datetime",
    "require_model_admission",
    "run_observation",
    "shadow_run_identity",
    "shadow_run_identity_payload",
    "validate_shadow_model_metadata",
    "verify_phase1_shadow_input",
]
